version: '3'
services:
    alerter:
       build: ./alerter
       ports:
       - "3005:25"
       env_file:
       - ./alerter/.env
       volumes:
       - ./alerter:/app
       depends_on:
       - "kafka"
       restart: always # will sometimes fail, if kafka takes too long
    zookeeper:
       image: wurstmeister/zookeeper
       ports: 
        - "2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_CREATE_TOPICS: "general:1:1,alert:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        depends_on: 
            - zookeeper