version: '3.1'
services:
    alertfrontend:
      container_name: alertfrontend
      build:
        context: ./alertfrontend/
        dockerfile: ./Dockerfile
      ports:
        - '1337:80'
    mysql_db:
      image: mysql:latest
      volumes:
        - ./mysql_db_data_container:/var/lib/mysql
        - ./mysql_db_init/:/docker-entrypoint-initdb.d/
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: rootpwd
        MYSQL_DATABASE: prestacoop
      ports:
        - 3306:3306
    adminer:
      image: adminer:latest
      hostname: ${KAFKA_HOST_NAME}
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db
      ports:
        - 8080:8080
    alerter:
       build: ./alerter
       ports:
       - "3005:25"
       env_file:
       - ./alerter/.env
       volumes:
       - ./alerter:/app
       depends_on:
       - "kafka"
       restart: always # will sometimes fail, if kafka takes too long
    alertbackend:
       build: ./alertbackend
       ports:
       - "3000:3000"
       env_file:
       - ./alertbackend/.env
       volumes:
       - ./alertbackend:/app
       depends_on:
       - "kafka"
       restart: always
    zookeeper:
       image: wurstmeister/zookeeper
       ports:
        - "2181"
    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_HOST_NAME}
            KAFKA_CREATE_TOPICS: "general:1:1,alert:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        depends_on:
            - zookeeper